name: today
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  extended_nested_scroll_view: ^6.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  googleapis: ^10.1.0
  googleapis_auth: ^1.4.0
  intl: ^0.18.1
  loading_more_list: ^5.0.3
  logger: ^1.3.0
  syncfusion_flutter_calendar: ^21.1.35
  table_calendar: ^3.0.8
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/3x/
