// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-1tMXv6o_Bknv7_88b078hDe1Ed_tCYI',
    appId: '1:618140231524:web:d318c29e90be178bcd7c71',
    messagingSenderId: '618140231524',
    projectId: 'today2023',
    authDomain: 'today2023.firebaseapp.com',
    storageBucket: 'today2023.appspot.com',
    measurementId: 'G-8PH9V0B94M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa0p22YD8UnUZZBp_-iy-0TTCoRnVrYxI',
    appId: '1:618140231524:android:3a2ab1f62855fa50cd7c71',
    messagingSenderId: '618140231524',
    projectId: 'today2023',
    storageBucket: 'today2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAKtVlSgaevD0HOgNSsMhlcR89CskVzrg',
    appId: '1:618140231524:ios:c484e808019c0054cd7c71',
    messagingSenderId: '618140231524',
    projectId: 'today2023',
    storageBucket: 'today2023.appspot.com',
    iosClientId: '618140231524-ubak70fqdnj3lg1k4v6r0ks728t6q4a6.apps.googleusercontent.com',
    iosBundleId: 'com.ambee.today',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAKtVlSgaevD0HOgNSsMhlcR89CskVzrg',
    appId: '1:618140231524:ios:16775267230a888ccd7c71',
    messagingSenderId: '618140231524',
    projectId: 'today2023',
    storageBucket: 'today2023.appspot.com',
    iosClientId: '618140231524-vkt7uhj67r7e8shkg26snjqst74ha882.apps.googleusercontent.com',
    iosBundleId: 'com.example.today',
  );
}
